/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import entidades.*;

public class viewMenu extends javax.swing.JFrame {
    Directorio directorio = new Directorio();
    
    public viewMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAgregarCliente = new javax.swing.JMenu();
        jmBuscarCliente = new javax.swing.JMenu();
        jmBorrarCliente = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jmAgregarCliente.setText("Agregar Cliente");
        jmAgregarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAgregarClienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmAgregarCliente);

        jmBuscarCliente.setText("Buscar Cliente");
        jmBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmBuscarClienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmBuscarCliente);

        jmBorrarCliente.setText("Borrar Cliente");
        jmBorrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmBorrarClienteMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmBorrarCliente);

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAgregarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAgregarClienteMouseClicked
        escritorio.removeAll();
        escritorio.repaint();
        viewAgregarCliente ag = new viewAgregarCliente(directorio);
        ag.setVisible(true);
        escritorio.add(ag);
        escritorio.moveToFront(ag);
    }//GEN-LAST:event_jmAgregarClienteMouseClicked

    private void jmBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmBuscarClienteMouseClicked
        escritorio.removeAll();
        escritorio.repaint();
        viewBuscarCliente bus = new viewBuscarCliente(directorio);
        bus.setVisible(true);
        escritorio.add(bus);
        escritorio.moveToFront(bus);
    }//GEN-LAST:event_jmBuscarClienteMouseClicked

    private void jmBorrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmBorrarClienteMouseClicked
        escritorio.removeAll();
        escritorio.repaint();
        viewBorrarCliente bor = new viewBorrarCliente(directorio);
        bor.setVisible(true);
        escritorio.add(bor);
        escritorio.moveToFront(bor);
    }//GEN-LAST:event_jmBorrarClienteMouseClicked

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAgregarCliente;
    private javax.swing.JMenu jmBorrarCliente;
    private javax.swing.JMenu jmBuscarCliente;
    private javax.swing.JMenu jmSalir;
    // End of variables declaration//GEN-END:variables
}
